name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: perl:threaded-buster

    steps:
      - uses: actions/checkout@v2

      - name: install with cpanm
        uses: perl-actions/install-with-cpanm@v1.1
        with:
          cpanfile: "cpanfile"
          sudo: false
      - run: ./create_blocklist_porn.pl
