name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        perl-version:
        - 5.32.1
    
    container:
      image: perl:${{ matrix.perl-version }}-threaded-buster

    steps:
      - uses: actions/checkout@v2

      - name: install with cpanm
        uses: perl-actions/install-with-cpanm@v1.1
        with:
          cpanfile: cpanfile
          sudo: false
      - run: /usr/local/share/perl5 ./create_blocklist_porn.pl
